name: build and Import NPM Package

on:
  push:
    branches:
      - main
      - Compiling-and-imports
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4

      - name: Installeer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Installeer dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Bundel met Rollup
        run: npm run rollup